In [1]:
# conda install graphviz

from sklearn import tree
from sklearn.datasets import load_iris
from sklearn import tree
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

#iris = load_iris()

###################################################
#iris = datasets.load_iris()
df = pd.read_csv('cluster_1110_2_20171113_addC.csv',index_col=0)
#print(df)
#print(df.iloc[:,0:3]) 
#print(df.iloc[:,21:22]) 

#X = iris.data
X = df.iloc[:,15:18]
#print(X)
#print(type(X))
X = np.array(X)
#print(X)
#X = X.tolist()
#print(type(X))
#X = np.reshape(X,len(X))
#print(X)

#y = iris.target
# ind_tjcr_fin_ult1 7:8信用卡       # TAX 6:7
#y = df.iloc[:,9:10]    # particular
y = df.iloc[:,14:15]     # 分群  14:15

### cluster_1110_2_20171113_addC.csv紀錄
### Funds	Taxes	Credit_Card	Securities	particular	Saving	Loans	Payroll
### 11799	39155	29918	    17494	    106130	   25366	83427	62375

y = np.array(y)
#print(y)
y=np.reshape(y,len(y))
#print(y)
#print(np.reshape(y,len(y)))

#print(type(y))

#iris.data = X
#iris.target = y
####################################################
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

print(X)
#print(y)


[[3 2 2]
 [4 2 3]
 [3 2 2]
 ..., 
 [5 1 3]
 [4 3 2]
 [3 3 3]]


In [17]:
'''
from sklearn import datasets
iris=datasets.load_iris()
X,y=iris.data,iris.target
#print(X,y)
#print(X)
#print(X[0:1])
print(type(X[0:1]))
'''

'\nfrom sklearn import datasets\niris=datasets.load_iris()\nX,y=iris.data,iris.target\n#print(X,y)\nprint(X)\n#print(X[0:1])\nprint(type(X[0:1]))\n'

In [25]:

clf = tree.DecisionTreeClassifier(max_depth=6,criterion='entropy')    # ,criterion='entropy'  default是 gini
#clf = clf.fit(iris.data, iris.target)
clf = clf.fit(X,y)
#print(clf)
#print(clf.score(X,y))



#############################################
import pickle #pickle模块

#保存Model(注:save文件夹要预先建立，否则会报错)
with open('save/clf1.pickle', 'wb') as f:
    pickle.dump(clf, f)

#读取Model
#with open('save/clf.pickle', 'rb') as f:
    #clf2 = pickle.load(f)
    #测试读取后的Model
    #print(clf2.predict(X[0:1]))
############################################

# [0]


from sklearn.externals import joblib #jbolib模块

#保存Model(注:save文件夹要预先建立，否则会报错)
joblib.dump(clf, 'save/clf2.pkl')

#读取Model
clf3 = joblib.load('save/clf2.pkl')

#测试读取后的Model
print(X[0:1])
print(clf3.predict(X[0:1]))

# [0]

#############################################




#tree.export_graphviz(clf,out_file='tree.dot')     


import graphviz 
dot_data = tree.export_graphviz(clf, out_file=None) 
graph = graphviz.Source(dot_data) 
#graph.render("bank.pdf") 
#tree.export_graphviz(clf,out_file='bank2.dot') 
dot_data = tree.export_graphviz(clf, out_file=None, 
                         feature_names=['age','Seniority','Income'],  
                         class_names=['G1','G2','G3'],
                         #class_names=['DontHave','Have'],
                         filled=True, rounded=True,  
                         special_characters=True
                               )  
#graph = graphviz.Source(dot_data)  
#graph
#graph.render("20171115_particular_6")


[[3 2 2]]
[1]


In [3]:
#clf.predict(iris.data[:1, :])
#clf.predict_proba(iris.data[:1, :])


NameError: name 'iris' is not defined