In [ ]:
%matplotlib inline


# SVM Exercise


A tutorial exercise for using different SVM kernels.

This exercise is used in the `using_kernels_tut` part of the
`supervised_learning_tut` section of the `stat_learn_tut_index`.



In [1]:
print(__doc__)


import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, svm
import pandas as pd

#iris = datasets.load_iris()
df = pd.read_csv('20171113_200.csv',index_col=0)
#print(df)
#print(df.iloc[:,0:3]) 
#print(df.iloc[:,21:22]) 

#X = iris.data
X = df.iloc[:,0:2]
#print(X)
X = np.array(X)
#print(X)
#X = X.tolist()
#print(type(X))
#X = np.reshape(X,len(X))
#print(X)

#y = iris.target
y = df.iloc[:,21:22]    # ind_tjcr_fin_ult1 信用卡
y = np.array(y)
#print(y)
y=np.reshape(y,len(y))
#print(y)
#print(np.reshape(y,len(y)))

#print(type(y))

Automatically created module for IPython interactive environment
[[ 44 171]
 [ 70 171]
 [ 62  71]
 [ 54 168]
 [ 56 171]
 [ 44 171]
 [ 55 171]
 [ 46 171]
 [ 53 170]
 [ 39 171]
 [ 42 171]
 [ 47 171]
 [ 55 171]
 [ 42 171]
 [ 67 171]
 [ 63 171]
 [ 43 171]
 [ 46 171]
 [ 48 171]
 [ 60 171]
 [ 41 171]
 [ 42 171]
 [ 44 171]
 [ 48 171]
 [ 62 160]
 [ 58  26]
 [ 56 171]
 [ 56 171]
 [ 48 171]
 [ 50 119]
 [ 60 171]
 [ 45 171]
 [ 41 171]
 [ 55 171]
 [ 45 171]
 [ 43 171]
 [ 61 171]
 [ 71 171]
 [ 40 131]
 [ 40 171]
 [ 41 171]
 [ 44 171]
 [ 77 171]
 [ 40 131]
 [ 48 171]
 [ 53 171]
 [ 50 171]
 [ 41 171]
 [ 53 171]
 [ 61 171]
 [ 55 171]
 [ 71 126]
 [ 50 171]
 [ 58 171]
 [ 52 171]
 [ 43 171]
 [ 68 171]
 [ 42 171]
 [ 39 137]
 [ 42 171]
 [ 57 171]
 [ 50 171]
 [ 64 171]
 [ 55 171]
 [ 44 171]
 [ 47 171]
 [ 54 171]
 [ 43 171]
 [ 36 171]
 [ 62 171]
 [ 42 171]
 [ 72 171]
 [ 51 171]
 [ 78 171]
 [ 63 167]
 [ 45 171]
 [ 68 171]
 [ 55 171]
 [ 42 171]
 [ 45 171]
 [ 46 171]
 [ 49 171]
 [ 72 171]
 [ 43 172]
 [ 41 171]


In [28]:
X = X[y != 0, :2]
#print(X)
#y = y[y != 0]
#print(y)

n_sample = len(X)
print(n_sample)    # 48


48


In [29]:
np.random.seed(0)
order = np.random.permutation(n_sample)
#print(order)
X = X[order]
#print(X)
y = y[order].astype(np.float)
#print(y)

In [32]:
X_train = X[:int(.9 * n_sample)]
X_train = X_train.astype(float)
X_train=X_train.reshape(X_train.shape)
print(X_train)
y_train = y[:int(.9 * n_sample)]
print(y_train)
X_test = X[int(.9 * n_sample):]
#print(X_test)
y_test = y[int(.9 * n_sample):]
print(y_test)


[[  56.  171.]
 [  55.  171.]
 [  60.  171.]
 [  40.  162.]
 [  55.  171.]
 [  73.  171.]
 [  46.  171.]
 [  44.  171.]
 [  45.  129.]
 [  53.   26.]
 [  43.  145.]
 [  33.  145.]
 [  42.  171.]
 [  62.  171.]
 [  46.  171.]
 [  53.  171.]
 [  72.  171.]
 [  40.  131.]
 [  46.  171.]
 [  47.  171.]
 [  53.  170.]
 [  43.  171.]
 [  51.  171.]
 [  52.  171.]
 [  42.  171.]
 [  50.  171.]
 [  50.  119.]
 [  42.  171.]
 [  77.  171.]
 [  51.  171.]
 [  40.  171.]
 [  55.  171.]
 [  31.   42.]
 [  45.  171.]
 [  43.  144.]
 [  41.  171.]
 [  44.  171.]
 [  54.  168.]
 [  78.  171.]
 [  41.  171.]
 [  62.  171.]
 [  43.  171.]
 [  55.  171.]]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.]


In [33]:
# fit the model
for fig_num, kernel in enumerate(('linear', 'rbf', 'poly')):
    clf = svm.SVC(kernel=kernel, gamma=10)
    clf.fit(X_train, y_train)

    plt.figure(fig_num)
    plt.clf()
    plt.scatter(X[:, 0], X[:, 1], c=y, zorder=10, cmap=plt.cm.Paired,
                edgecolor='k', s=20)

    # Circle out the test data
    plt.scatter(X_test[:, 0], X_test[:, 1], s=80, facecolors='none',
                zorder=10, edgecolor='k')

    plt.axis('tight')
    x_min = X[:, 0].min()
    x_max = X[:, 0].max()
    y_min = X[:, 1].min()
    y_max = X[:, 1].max()

    XX, YY = np.mgrid[x_min:x_max:200j, y_min:y_max:200j]
    Z = clf.decision_function(np.c_[XX.ravel(), YY.ravel()])

    # Put the result into a color plot
    Z = Z.reshape(XX.shape)
    plt.pcolormesh(XX, YY, Z > 0, cmap=plt.cm.Paired)
    plt.contour(XX, YY, Z, colors=['k', 'k', 'k'],
                linestyles=['--', '-', '--'], levels=[-.5, 0, .5])

    plt.title(kernel)
plt.show()

ValueError: The number of classes has to be greater than one; got 1